name: Setup
description: 'Setup stuff'
runs:
  using: "composite"
  steps:
    - name: set up JDK 24
      uses: actions/setup-java@v5.0.0
      with:
        distribution: 'zulu'
        java-version: '24'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
